#Desafio 4 - Faça um programa que leia algo pelo teclado
# e mostre na tela o seu tipo primitivo e todas as informações possíveis.( Usando .is...)

algo = input('Digite Algo: ')
print('------------------')
print('| Tipo Primitivo |')
print('------------------')
print('O que você digitou contém letras e números: ', algo.isalnum())
print('O que você digitou é somente letras: ', algo.isalpha())
print('O que você digitou está na tabela Ascii: ', algo.isascii())
print('O que você digitou é um digito: ', algo.isdigit())
print('O que você digitou está em letras minúsculas: ', algo.islower())
print('O que você digitou é decimal: ', algo.isdecimal())
print('O que você digitou não começa com números e não tem espaço: ', algo.isidentifier())
print('O que você digitou pode ser impresso: ', algo.isprintable())
print('O que você digitou é um espaço: ', algo.isspace())
print('O que você digitou está capitalizada: ', algo.istitle())
print('O que você digitou contém somente números: ', algo.isnumeric())
print('O que você digitou está em letras maiúsculas: ', algo.isupper())